<?php

define('JSTREE_PATH', drupal_get_path('module', 'jstree') . '/js/');

function jstree_add($files=array()) {
  static $jstree_core,$loaded_files;

  $jstree_path = JSTREE_PATH;

  if (!is_array($files)) {
    $files = array($files);
  }

  if (!isset($jstree_core)) {
    $jstree_core = TRUE;
    jstree_add(array('css','tree_component.min'));
    drupal_add_js(array('jstree_path' => base_path() . JSTREE_PATH), 'setting');
    drupal_add_css(JSTREE_PATH . 'tree_component.css');
  }

  // Loop through list of files to include and add them to the page.
  foreach ($files as $file) {
    // Load other files.
    if (!isset($loaded_files[$file])) {
	  $file_path = "$file.js";
      $js_path = $jstree_path . $file_path;
      drupal_add_js($js_path);
      $loaded_files[$file] = $js_path;
    }
  }
}


/**
 * Return the version of jsTree installed.
 */
function jstree_get_version() {
  $version = 0;

  if (file_exists(JSTREE_PATH . '/version.txt')) {
    $version = file_get_contents(JSTREE_PATH . '/version.txt');
  }

  return $version;
}








