<?php

/**
 * lifedesk_foot.module
 * Forces a site to include a footer that can only be changed by editing the source code
 */

/**
 * Implementation of hook_block
 */
function lifedesk_foot_block($op = 'list', $delta = 0) {
  global $theme_key;
  if ($op == 'list') {
    $default_placement = 'footer';
    $regions = system_region_list($theme_key);
    if (isset($regions) && array_key_exists($default_placement, $regions)) {
      $blocks[0]['region'] = $default_placement;
    } else {
      $blocks[0]['region'] = BLOCK_REGION_NONE;
    }
    $blocks[0]['info'] = t('LifeDesk Footer');
    return $blocks;
  }
  else {
  if ($op == 'view') {
    $block['subject'] = t('LifeDesk Footer');
      $block['content'] = _lifedesk_foot_getfoot();
  }
  return $block;
  }
}

/**
 * Implementation of hook_footer()
 */
function lifedesk_foot_footer($main=0){
  global $user, $conf;

  $domain = $conf['_lifedesks_domain'];

  $string = '';

  if($user->uid != 1) {
    $string .= '<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src=\'" + gaJsHost + "google-analytics.com/ga.js\' type=\'text/javascript\'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
    try {
    var pageTracker = _gat._getTracker("UA-8484689-1");
    pageTracker._setDomainName(".lifedesks.org");
    pageTracker._trackPageview();
    } catch(err) {}</script>';
  }

  return $string;
}

function _lifedesk_foot_getfoot() {
  global $conf;
  $domain = $conf['_lifedesks_domain'];

  drupal_add_css(drupal_get_path('module', 'lifedesk_foot') . '/css/lifedesk_foot.css');

  $output = t('Member of the !lifedesk Community', array('!lifedesk' => l(t('LifeDesk'), 'http://www.' . $domain, array('absolute' => true))));

  return $output;
}
