<?php
// $Id: cooliris_lifedesk_gallery.module,v 1.1.4.9 2008/07/18 16:25:23 dshorthouse Exp $

/**
 * @file Enables Cooliris feeds and/or Cooliris (Lite) for the LifeDesk taxongallery module.
 *
 */

/**
 * Implementation of hook_menu().
 */
function cooliris_lifedesk_gallery_menu() {
  $items = array();
  $items['gallery/mediarss'] = array(
    'title' => 'PicLens RSS Feed',
    'access arguments' => array('access content'),
    'page callback' => 'cooliris_create_feed',
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/mediarss/gallery'] = array(
    'title' => 'Image Gallery MediaRSS',
    'access arguments' => array('administer cooliris'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cooliris_lifedesk_gallery_admin_settings'),
    'description' => 'Configure Cooliris support for the Image Gallery in LifeDesk.',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Menu callback for Cooliris settings.
 */
function cooliris_lifedesk_gallery_admin_settings() {
  $form['image_gallery'] = array(
    '#type' => 'fieldset',
    '#title' => t('Image Gallery'),
  );
  // get existing labels from image, leaving out default thumbnail.
  $sizes = image_get_sizes();
  foreach ($sizes as $key => $val) {
    if ($key != 'thumbnail') {
      $options[$key] = $val['label'];
    }
  }
  $form['image_gallery']['cooliris_lifedesk_gallery_content'] = array(
    '#title' => t('Image size content'),
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => variable_get('cooliris_lifedesk_gallery_content', 'preview'),
    '#description' => t('Choose which image size to use for the content.<br/>Note: the thumbnail will automatically be the standard image thumbnail.'),
  );
  $form['image_gallery']['cooliris_lifedesk_link_to'] = array(
    '#type' => 'radios',
    '#title' => t('Link preview back to'),
    '#options' => array('image' => t('Direct image link'), 'node' => t('Image page')),
    '#default_value' => variable_get('cooliris_lifedesk_link_to', 'image'),
  );
  $form['image_gallery']['cooliris_lifedesk_gallery_js'] = array(
    '#type' => 'checkbox',
    '#title' => t('Lite javascript for image galleries.'),
    '#description' => t('Toggle this checkbox to add support for the Lite version of Cooliris.<br/>This will add javascript to the head of your document.'),
    '#default_value' => variable_get('cooliris_lifedesk_gallery_js', 0),
  );
  $form['image_gallery']['cooliris_lifedesk_gallery_link'] = array(
    '#type' => 'checkbox',
    '#title' => t('CoolIris Lite link for image galleries.'),
    '#description' => t('Toggle this checkbox to add a link as a message to start the Cooliris Lite slideshow.'),
    '#default_value' => variable_get('cooliris_lifedesk_gallery_link', 0),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_mediarss_items.
 */
function cooliris_lifedesk_gallery_mediarss_items($args) {
  global $base_url;
  // Allow images to be sorted in a useful order.
  if(!$args) {
    $query = "SELECT n.nid FROM {node} n WHERE n.status = 1 AND n.type = 'image' ORDER BY n.created desc";
    $query_pager = "SELECT COUNT(DISTINCT(n.nid)) FROM {node} n WHERE n.status=1 AND n.type='image'";
  }
  
  $content = variable_get('cooliris_image_gallery_content', '_original');
  $result = pager_query($query,variable_get('image_images_per_page', 6), 0, $query_pager);
  
  while ($row = db_fetch_object($result)) {
    $node = node_load($row->nid);
    $image_info = image_get_info($node->images[$content]);
    $link = key($node->taxonomy) ? $base_url . '/pages/' . key($node->taxonomy) : $base_url . '/image_gallery';
    if(fopen($node->images['thumbnail'], "r")) {
	    $item = array(
	      'title' => $node->title . ' (' . variable_get('site_name', 'LifeDesk') . ')',
	      'link' => $link,
	      'pubdate' => gmdate('D, d M Y H:i:s O',$node->created),
	      'thumbnail' => ($node->images['paths'][IMAGE_THUMBNAIL]) ? $base_url . '/' . $node->images['paths'][IMAGE_THUMBNAIL] : file_create_url($node->images['thumbnail']),
	      'content_url' => ($node->images['paths'][IMAGE_ORIGINAL]) ? $base_url . '/' . $node->images['paths'][IMAGE_ORIGINAL] : file_create_url($node->images[$content]),
	      'type' => $image_info['mime_type'],
	      'height' => $image_info['height'],
	      'width' => $image_info['width'],
	    );
    }
    if (variable_get('cooliris_image_link_to', 'image') == 'node') {
      $item['link'] = url('node/'. $node->nid, array('absolute' => TRUE));
    }
    $items .= mediarssapi_format_item($item);
  }
  return $items;
}

function cooliris_create_feed() {
	  if (user_access('access content')) {
	    $args = func_get_args();
	    $module = check_plain(array_shift($args));
	    $items = module_invoke('cooliris_lifedesk_gallery', 'mediarss_items', $args);
	    if (!empty($items)) {
	      mediarssapi_rss($items);
	    }
	  }
}
